node {
    stage('Checkout AuthService') {
        git branch: 'main', url: 'https://github.com/hunterr22/metro-auth.git'
    }

    stage('Gradle Build - AuthService') {
        sh './auth/gradlew clean build -p ./auth -Dorg.gradle.java.home=//usr/lib/jvm/java-11-openjdk-amd64'
    }

    stage('Gradle Bootjar-Package - AuthService') {
        sh './auth/gradlew bootjar -p ./auth -Dorg.gradle.java.home=//usr/lib/jvm/java-11-openjdk-amd64'
    }

    stage('User Acceptance Test - AuthService') {
    
        def response= input message: 'Is this build good to go?',
            parameters: [choice(choices: 'Yes\nNo',
            description: '', name: 'Pass')]
        
        if(response=="Yes") {
            stage('Release - AuthService') {
            sh './auth/gradlew build -x test -p ./auth -Dorg.gradle.java.home=//usr/lib/jvm/java-11-openjdk-amd64'
            sh 'echo AuthService is ready to release'
            }
        }
    }
}